--- Types
---@class ide.Plugins
---@field loaded table<string, {spec: vim.pack.Spec, path: string}>
---
---@class settings.PluginData
---@field enabled ?boolean disable or enable plugin, default is enabled
---@field build ?fun(event: settings.PackEvent) function to run after plugin is installed or updated
---
---@class vim.pack.Spec
---@diagnostic disable-next-line: duplicate-doc-field
---@field data ?settings.PluginData
---
---@class settings.PackEvent
---@field active boolean
---@field spec vim.pack.Spec
---@field kind 'install' | 'update' | 'remove'
---
---@alias vim.pack.OnLoad fun(plug_data: {spec: vim.pack.Spec, path: string})
